### ISSUE TITLE
Lots of bugs after update

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#45] opened 2023-02-06 00:43 UTC
![Screenshot_2](https://user-images.githubusercontent.com/54962940/216856311-81474dfd-9d37-4fdc-89ae-563aaeba15c0.png)
![Screenshot_3](https://user-images.githubusercontent.com/54962940/216856323-66c7c3ad-d856-4231-8328-52b8ccf31ac9.png)
![Screenshot_4](https://user-images.githubusercontent.com/54962940/216856346-c9ecd335-5b8e-4b53-9ce7-1b4feb2479ee.png)
![Screenshot_5](https://user-images.githubusercontent.com/54962940/216856399-82386f9c-a12c-4cac-a158-77cdc0223f29.png)

Players cannot use the command (k home), enter, for example, the graphical menu of the tower 

I can already use it, I even tried to give this player administrator rights (like I have) the effect is that the errors still occur

I need to go back to the previous version :(

**Comment by Ksewedo5** [comment] 2023-02-06 00:51
After downgrading to version 1.14.19 everything went back to normal.

**Comment by CryptoMorin** [comment] 2023-02-06 08:58
Hi the first few errors are due to outdated config files. Please delete `config.yml`, `misc-upgrades.yml` and `chat.yml` while the server is **offline**.
For the last error, I'll have to take a look.

**Comment by CryptoMorin** [comment] 2023-02-08 18:43
As for the last error, I was unable to reproduce it. Please provide a step by step reproduction.

**Comment by Ksewedo5** [comment] 2023-02-08 19:20
https://youtube.com/shorts/xEI5Q2052Mc  
Me and user Karolina have the same permissions. (./op) 
I have absolutely no idea why I have no problems and user Karolina already does

**Comment by Ksewedo5** [comment] 2023-02-08 19:37
This update broke almost every configuration and language file. Additionally, the record of kingdoms was destroyed
![Screenshot_3](https://user-images.githubusercontent.com/54962940/217633128-bb9ed80b-bf8e-4387-ab10-405fd6913dec.png)

The language file looks completely different, will I have to spend a week/2 to translate the plugin with each update?


This is not the first time configuration files have been changed... Please add support for old configuration files or migration capabilities.

**Comment by Ksewedo5** [comment] 2023-02-08 19:40
After downloading Polish (generally very poor translation) there is a wall of errors
![Screenshot_4](https://user-images.githubusercontent.com/54962940/217634357-dcec14aa-694f-41d1-a3b0-23ea58d110dc.png)
![Screenshot_5](https://user-images.githubusercontent.com/54962940/217634361-dfe6725f-4031-4a64-af7e-ceafeb0f242d.png)

**Comment by CryptoMorin** [comment] 2023-02-09 04:46
> Additionally, the record of kingdoms was destroyed

It's either caused by a relevant error that you haven't shown to me yet, or it's caused by crashes or server force stops.

> This update broke almost every configuration and language file.
> The language file looks completely different, will I have to spend a week/2 to translate the plugin with each update?
> This is not the first time configuration files have been changed... Please add support for old configuration files or migration capabilities.

That's why they're called major updates. I won't stop improving the plugin just because it "breaks" with outdated configs. But yes, I agree there should be a migration feature, I was thinking about it for a long time, but I haven't gotten around it yet.

As for language files, this update in general was very focused on making the entire plugin multi-lingual, so yes breaking changes were expected.

> After downloading Polish (generally very poor translation) there is a wall of errors
This was fixed in v1.15.3.1

**Comment by Ksewedo5** [comment] 2023-02-09 05:08
> That's why they're called major updates. I won't stop improving the plugin just because it "breaks" with outdated configs. But yes, I agree there should be a migration feature, I was thinking about it for a long time, but I haven't gotten around it yet.  

A good example could be ChatControl from kangarko, language files were changed with updates, but variables were simply added to the file and information was shown in the console what you need to pay attention to, the fact ... that I can add Polish from a 2-year backup and it will work

> This was fixed in v1.15.3.1
As a side note, translations are purely community-based. I cannot update them or fix typos simply because I don't speak those languages. 


Anyway, I need to translate. I can add Polish using "pull requests"


Please, next time you update, think to make these files compatible so you don't do the same thing :))

**Comment by CryptoMorin** [comment] 2023-02-10 05:30
The latest version now has a config migration system when automatic config updates are enabled.

**Closed by CryptoMorin** 2023-02-10 05:30 UTC
Labels: bug, question
