### ISSUE TITLE
The nexus hologram not removed after moving the nexus.

### ISSUE THREAD

**Issue by Cloak3** [CryptoMorin/KingdomsX#35] opened 2022-08-05 14:19 UTC
![image](https://user-images.githubusercontent.com/28222513/183093777-9eb552b2-01fb-44e7-9264-a1e53f9f359a.png)
If I place the nexus somewhere, go far away (e.g. /tp ~99999 ~ ~99999), claim a chunk, and move the nexus there using "/k nexus", the original beacon block disappears as expected, while the hologram remains.

**Server version:** paper-1.19.1-87
**Tested plugin versions:** 1.13.12, 1.14.0-BETA

**Comment by CryptoMorin** [comment] 2022-08-06 04:26
I tried this with the latest 1.14.2-BETA I did everything as you described. I was unable to reproduce it.

**Comment by CryptoMorin** [comment] 2022-08-30 20:05
This has been fixed in v1.14.6-BETA

**Closed by CryptoMorin** 2022-08-30 20:05 UTC
Labels: bug
