### ISSUE TITLE
Error in displaying numbers in Nexus GUI - NBSP character separator

### ISSUE THREAD

**Issue by Ksewedo5** [CryptoMorin/KingdomsX#13] opened 2021-01-19 21:47 UTC
![Screenshot_7](https://user-images.githubusercontent.com/54962940/105097053-45622e80-5aa8-11eb-9299-3deafd9eb556.png)

**Comment by CryptoMorin** [comment] 2021-01-20 03:12
I'm unable to reproduce this. This seems to be an issue with the system's Java version or locale settings.

**Comment by Ksewedo5** [comment] 2021-01-20 07:30
Java 8 update 271 (build 1.8.0_271-b09) Windows 10 Polish, Server 1.16.4(PaperSpigot) Maybe it will be useful information, I saw the same error on other servers

**Comment by AfkF24** [comment] 2021-01-21 18:16
Most likely a charset issue or you're using a resourcepack that doesn't display that character correctly (especially since you mentioned it's happening on other servers too).

Try changing your Minecraft language from Polish to English and see if it's still happening.

**Comment by Ksewedo5** [comment] 2021-01-22 00:15
I'm using the default minecraft textures. The error also appears in the English version

**Comment by CryptoMorin** [comment] 2021-01-23 19:45
Fixed in v1.10.14

**Closed by CryptoMorin** 2021-01-23 19:45 UTC
Labels: bug
