### ISSUE TITLE
Strange reaction occurred with the CoreProtect-22.4 plugin

### ISSUE THREAD

**Issue by Leoparking** [CryptoMorin/KingdomsX#63] opened 2024-07-11 14:34 UTC
If the server loads the Kingdom plugin and enables the "explosion block scattering effect"（in misc-upgrades.yml） of the Kingdom plugin, coreprotect will not be able to recover the damage caused by the explosion (please see the video, this is the behavior before and after loading the Kingdom plugin, you can see that the explosion block will fly up when the Kingdom plugin is already loaded)
(Whether within the kingdom or not, and whether the operator has joined the kingdom)
<img width="323" alt="a979a733ade86b4b555ddafd18ee8c9e" src="https://github.com/CryptoMorin/KingdomsX/assets/141799770/49347a2b-75a3-4649-8edf-9fe1d9d7168f">

### Here is a video you can watch
https://discord.com/channels/429132410748141579/1260965696880513124

### This is the same issue as the CoreProtect plugin
https://github.com/PlayPro/CoreProtect/issues/585

**Comment by CryptoMorin** [comment] 2024-07-12 06:35
I'm closing this in favor of the Discord issue. But I couldn't reproduce it as shown in discord.

**Closed by CryptoMorin** 2024-07-12 06:35 UTC
Labels: bug, duplicate, invalid
